read/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from account import views

urlpatterns = [
        url(r'^admin/', include(admin.site.urls)),
        url(r'^$', views.homepage, name='homepage'),
        url(r'^account/', include('account.urls')),  
        url(r'^student/', include('student.urls')),
        url(r'^teacher/', include('teacher.urls')),    
]

teacher/urls.py
# -*- coding: UTF-8 -*-
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from teacher.views import ClassroomListView, ClassroomCreateView, WorkListView, WorkCreateView, ForumListView, ForumCreateView, ForumContentListView, ForumContentCreateView

urlpatterns = [
    # 班級
    url(r'^classroom/$', login_required(views.ClassroomListView.as_view()), name='classroom-list'),
    url(r'^classroom/add/$', login_required(views.ClassroomCreateView.as_view()), name='classroom-add'),
    url(r'^classroom/edit/(?P<classroom_id>\d+)/$', views.classroom_edit, name='classroom-edit'),
    # 退選
    url(r'^unenroll/(?P<enroll_id>\d+)/(?P<classroom_id>\d+)/$', views.unenroll),  	
    # 搜查線
    url(r'^work/(?P<classroom_id>\d+)/$', login_required(WorkListView.as_view()), name='work-list'),
    url(r'^work/add/(?P<classroom_id>\d+)/$', login_required(WorkCreateView.as_view()), name='work-add'),
    url(r'^work/edit/(?P<classroom_id>\d+)/$', views.work_edit, name='work-edit'),  
    url(r'^work/class/(?P<classroom_id>\d+)/(?P<work_id>\d+)/$', views.work_class, name='work-class'),  
    # 討論區
    url(r'^forum/(?P<classroom_id>\d+)/$', login_required(ForumListView.as_view()), name='forum-list'),
    url(r'^forum/add/(?P<classroom_id>\d+)/$', login_required(ForumCreateView.as_view()), name='forum-add'),
    url(r'^forum/download/(?P<content_id>\d+)/$', views.forum_download, name='forum-add'),  
    url(r'^forum/content/(?P<forum_id>\d+)/$', login_required(ForumContentListView.as_view()), name='forum-content'), 
    url(r'^forum/content/add/(?P<forum_id>\d+)/$', login_required(ForumContentCreateView.as_view()), name='forum-content-add'),
    url(r'^forum/content/delete/(?P<forum_id>\d+)/(?P<content_id>\d+)/$', views.forum_delete, name='forum-content-delete'),   
    url(r'^forum/class/(?P<classroom_id>\d+)/(?P<forum_id>\d+)/$', views.forum_class, name='forum-class'),  
]

teacher/models.py
# -*- coding: UTF-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# 班級
class Classroom(models.Model):
    # 班級名稱
    name = models.CharField(max_length=30)
    # 選課密碼
    password = models.CharField(max_length=30)
    # 授課教師
    teacher_id = models.IntegerField(default=0)
    # 是否開放分組
    group_open = models.BooleanField(default=True)
    # 組別人數
    group_size = models.IntegerField(default=4)

    @property
    def teacher(self):
        return User.objects.get(id=self.teacher_id)  
        
    def __unicode__(self):
        return self.name
      
#搜查線
class TWork(models.Model):
    title = models.CharField(max_length=250)
    teacher_id = models.IntegerField(default=0)		
    classroom_id = models.IntegerField(default=0)
    time = models.DateTimeField(default=timezone.now)    
    
#討論區
class FWork(models.Model):
    title = models.CharField(max_length=250)
    teacher_id = models.IntegerField(default=0)		
    classroom_id = models.IntegerField(default=0)
    time = models.DateTimeField(default=timezone.now)    

class FContent(models.Model):
    forum_id =  models.IntegerField(default=0)
    content_type = models.IntegerField(default=0)
    content_title = models.CharField(max_length=250,null=True,blank=True)     
    content_link = models.CharField(max_length=250,null=True,blank=True) 
    content_youtube = models.CharField(max_length=250,null=True,blank=True) 
    content_file = models.FileField(blank=True,null=True)
    content_filename = models.CharField(max_length=20,null=True,blank=True)     

teacher/forms.py
# -*- coding: utf-8 -*-
from django import forms
from teacher.models import Classroom, TWork, FWork, FContent
from student.models import SWork

# 新增一個課程表單
class ClassroomForm(forms.ModelForm):
        class Meta:
           model = Classroom
           fields = ['name','password']
        
        def __init__(self, *args, **kwargs):
            super(ClassroomForm, self).__init__(*args, **kwargs)
            self.fields['name'].label = "班級名稱"
            self.fields['password'].label = "選課密碼"

# 新增一個作業
class WorkForm(forms.ModelForm):
        class Meta:
           model = TWork
           fields = ['title']
        
        def __init__(self, *args, **kwargs):
            super(WorkForm, self).__init__(*args, **kwargs)
            self.fields['title'].label = "作業名稱"
            
# 作業評分表單           
class ScoreForm(forms.ModelForm):
        RELEVANCE_CHOICES = (
            (100, "你好棒(100分)"),
            (90, "90分"),
            (80, "80分"),
            (70, "70分"),
            (60, "60分"),
        )
        score = forms.ChoiceField(choices = RELEVANCE_CHOICES, required=True, label="分數")
        #if user.groups.all()[0].name == 'teacher': 
        assistant = forms.BooleanField(required=False,label="小老師")
    
        class Meta:
           model = SWork
           fields = ['score']
		   
        def __init__(self, user, *args, **kwargs): 
            super(ScoreForm, self).__init__(*args, **kwargs)	
            if user.groups.all().count() == 0 :
                del self.fields['assistant']
Check_CHOICES = (
    (100, "你好棒(100分)"),
    (90, "90分"),
    (80, "80分"),
    (70, "70分"),
    (60, "60分"),
    (40, "40分"),
    (20, "20分"),
    (0, "0分"),			
)		

# 新增一個作業
class ForumForm(forms.ModelForm):
        class Meta:
           model = FWork
           fields = ['title']
        
        def __init__(self, *args, **kwargs):
            super(ForumForm, self).__init__(*args, **kwargs)
            self.fields['title'].label = "作業名稱"
						
# 新增一個作業
class ForumContentForm(forms.ModelForm):
        class Meta:
           model = FContent
           fields = ['forum_id', 'content_type', 'content_title', 'content_link', 'content_youtube', 'content_file']
        
        def __init__(self, *args, **kwargs):
            super(ForumContentForm, self).__init__(*args, **kwargs)
            self.fields['forum_id'].required = False		
            self.fields['content_title'].required = False						
            self.fields['content_link'].required = False
            self.fields['content_youtube'].required = False
            self.fields['content_file'].required = False

teacher/views.py
# -*- coding: UTF-8 -*-
from django.shortcuts import render
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.views.generic import ListView, DetailView, CreateView
from teacher.models import Classroom, TWork, FWork, FContent
from student.models import Enroll, EnrollGroup, SWork, Assistant
from .forms import ClassroomForm, WorkForm, ForumForm, ForumContentForm
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.storage import FileSystemStorage
import os
from uuid import uuid4
from django.conf import settings
from wsgiref.util import FileWrapper
from django.http import HttpResponse
# 判斷是否為授課教師
def is_teacher(user, classroom_id):
    return user.groups.filter(name='teacher').exists() and Classroom.objects.filter(teacher_id=user.id, id=classroom_id).exists()



# 列出所有課程
class ClassroomListView(ListView):
    model = Classroom
    context_object_name = 'classrooms'
    template_name = 'teacher/classroom.html'
    paginate_by = 20
    def get_queryset(self):      
        queryset = Classroom.objects.filter(teacher_id=self.request.user.id).order_by("-id")
        return queryset
        
#新增一個課程
class ClassroomCreateView(CreateView):
    model = Classroom
    form_class = ClassroomForm
    template_name = 'form.html'    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.teacher_id = self.request.user.id
        self.object.save()
        # 將教師設為0號學生
        enroll = Enroll(classroom_id=self.object.id, student_id=self.request.user.id, seat=0)
        enroll.save()            
        return redirect("/teacher/classroom")        
        
# 修改選課密碼
def classroom_edit(request, classroom_id):
    # 限本班任課教師
    if not is_teacher(request.user, classroom_id):
        return redirect("homepage")
    classroom = Classroom.objects.get(id=classroom_id)
    if request.method == 'POST':
        form = ClassroomForm(request.POST)
        if form.is_valid():
            classroom.name =form.cleaned_data['name']
            classroom.password = form.cleaned_data['password']
            classroom.save()
            return redirect('/teacher/classroom')
    else:
        form = ClassroomForm(instance=classroom)

    return render_to_response('form.html',{'form': form}, context_instance=RequestContext(request))        
    
# 退選
def unenroll(request, enroll_id, classroom_id):
    # 限本班任課教師
    if not is_teacher(request.user, classroom_id):
        return redirect("homepage")    
    enroll = Enroll.objects.get(id=enroll_id)
    enroll.delete()
    classroom_name = Classroom.objects.get(id=classroom_id).name
    return redirect('/student/classmate/'+classroom_id)  
  
# 列出所有課程
class WorkListView(ListView):
    model = TWork
    context_object_name = 'works'
    paginate_by = 20
    def get_queryset(self):
        queryset = TWork.objects.filter(teacher_id=self.request.user.id, classroom_id=self.kwargs['classroom_id']).order_by("-id")
        return queryset
			
    def get_context_data(self, **kwargs):
        context = super(WorkListView, self).get_context_data(**kwargs)
        context['classroom_id'] = self.kwargs['classroom_id']
        return context	
        
#新增一個課程
class WorkCreateView(CreateView):
    model = TWork
    form_class = WorkForm
    template_name = "form.html"
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.teacher_id = self.request.user.id
        self.object.classroom_id = self.kwargs['classroom_id']
        self.object.save()  
  
        return redirect("/teacher/work/"+self.kwargs['classroom_id'])        
        
# 修改選課密碼
def work_edit(request, classroom_id):
    # 限本班任課教師
    if not is_teacher(request.user, classroom_id):
        return redirect("homepage")
    classroom = Classroom.objects.get(id=classroom_id)
    if request.method == 'POST':
        form = ClassroomForm(request.POST)
        if form.is_valid():
            classroom.name =form.cleaned_data['name']
            classroom.password = form.cleaned_data['password']
            classroom.save()
                  
            return redirect('/teacher/classroom')
    else:
        form = ClassroomForm(instance=classroom)

    return render_to_response('form.html',{'form': form}, context_instance=RequestContext(request))        
    			
# 列出某作業所有同學名單
def work_class(request, classroom_id, work_id):
    enrolls = Enroll.objects.filter(classroom_id=classroom_id)
    classroom_name = Classroom.objects.get(id=classroom_id).name
    classmate_work = []
    scorer_name = ""
    for enroll in enrolls:
        try:    
            work = SWork.objects.get(student_id=enroll.student_id, index=work_id)
            if work.scorer > 0 :
                scorer = User.objects.get(id=work.scorer)
                scorer_name = scorer.first_name
            else :
                scorer_name = "1"
        except ObjectDoesNotExist:
            work = SWork(index=work_id, student_id=1)
        try:
            group_name = EnrollGroup.objects.get(id=enroll.group).name
        except ObjectDoesNotExist:
            group_name = "沒有組別"
        assistant = Assistant.objects.filter(classroom_id=classroom_id, student_id=enroll.student_id, lesson=work_id)
        if assistant.exists():
            classmate_work.append([enroll,work,1, scorer_name, group_name])
        else :
            classmate_work.append([enroll,work,0, scorer_name, group_name])   
    def getKey(custom):
        return custom[0].seat
	
    classmate_work = sorted(classmate_work, key=getKey)
    
        
    return render_to_response('teacher/twork_class.html',{'classmate_work': classmate_work, 'classroom_id':classroom_id, 'index': work_id}, context_instance=RequestContext(request))
	
# 列出所有課程
class ForumListView(ListView):
    model = FWork
    context_object_name = 'works'
    template_name = "teacher/forum_list.html"		
    paginate_by = 20
    def get_queryset(self):
        queryset = FWork.objects.filter(teacher_id=self.request.user.id, classroom_id=self.kwargs['classroom_id']).order_by("-id")
        return queryset
			
    def get_context_data(self, **kwargs):
        context = super(ForumListView, self).get_context_data(**kwargs)
        context['classroom_id'] = self.kwargs['classroom_id']	
        return context	
        
#新增一個課程
class ForumCreateView(CreateView):
    model = FWork
    form_class = ForumForm
    template_name = "form.html"
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.teacher_id = self.request.user.id
        self.object.classroom_id = self.kwargs['classroom_id']
        self.object.save()  
  
        return redirect("/teacher/forum/"+self.kwargs['classroom_id'])        
            			
# 列出某作業所有同學名單
def forum_class(request, classroom_id, work_id):
    enrolls = Enroll.objects.filter(classroom_id=classroom_id)
    classroom_name = Classroom.objects.get(id=classroom_id).name
    classmate_work = []
    scorer_name = ""
    for enroll in enrolls:
        try:    
            work = SWork.objects.get(student_id=enroll.student_id, index=work_id)
            if work.scorer > 0 :
                scorer = User.objects.get(id=work.scorer)
                scorer_name = scorer.first_name
            else :
                scorer_name = "1"
        except ObjectDoesNotExist:
            work = SWork(index=work_id, student_id=1)
        try:
            group_name = EnrollGroup.objects.get(id=enroll.group).name
        except ObjectDoesNotExist:
            group_name = "沒有組別"
        assistant = Assistant.objects.filter(classroom_id=classroom_id, student_id=enroll.student_id, lesson=work_id)
        if assistant.exists():
            classmate_work.append([enroll,work,1, scorer_name, group_name])
        else :
            classmate_work.append([enroll,work,0, scorer_name, group_name])   
    def getKey(custom):
        return custom[0].seat
	
    classmate_work = sorted(classmate_work, key=getKey)
    
        
    return render_to_response('teacher/twork_class.html',{'classmate_work': classmate_work, 'classroom_id':classroom_id, 'index': work_id}, context_instance=RequestContext(request))

# 列出所有課程
class ForumContentListView(ListView):
    model = FContent
    context_object_name = 'contents'
    template_name = "teacher/forum_content.html"		
    paginate_by = 20
    def get_queryset(self):
        queryset = FContent.objects.filter(forum_id=self.kwargs['forum_id']).order_by("-id")
        return queryset
			
    def get_context_data(self, **kwargs):
        context = super(ForumContentListView, self).get_context_data(**kwargs)
        context['forum_id'] = self.kwargs['forum_id']
        return context	
			
#新增一個課程
class ForumContentCreateView(CreateView):
    model = FContent
    form_class = ForumContentForm
    template_name = "teacher/forum_form.html"
    def form_valid(self, form):
        self.object = form.save(commit=False)
        work = FContent(forum_id=self.object.forum_id)
        if self.object.content_type == 1:
            work.content_type = 1
            work.content_title = self.object.content_title
            work.content_link = self.object.content_link
        if self.object.content_type  == 2:
            work.content_type = 2					
            work.content_youtube = self.object.content_youtube
        if self.object.content_type  == 3:
            work.content_type = 3
            myfile = self.request.FILES['content_file']
            fs = FileSystemStorage()
            filename = uuid4().hex
            work.content_title = myfile.name
            work.content_filename = filename
            fs.save("static/upload/"+filename, myfile)	
        work.save()         
  
        return redirect("/teacher/forum/content/"+self.kwargs['forum_id'])  

    def get_context_data(self, **kwargs):
        ctx = super(ForumContentCreateView, self).get_context_data(**kwargs)
        ctx['forum_id'] = self.kwargs['forum_id']

templates/teacher/classroom.html
{% extends "base.html" %}
{% block content %}
        <a href="/teacher/classroom/add">新增班級</a> 
        <table>
            <tr>
                <td>名稱</td>
                <td>密碼</td>
                <td>功能</td>
        {% for classroom in classrooms %}
            <tr>
            <td>{{classroom.name}}</td>
            <td>{{classroom.password}}</td>
            <td>
                <a href="/teacher/classroom/edit/{{classroom.id}}">修改</a>|			
                <a href="/student/classmate/{{classroom.id}}">學生</a>|
                <a href="/teacher/work/{{classroom.id}}">搜查線</a>|   
                <a href="/teacher/forum/{{classroom.id}}">討論區</a>|                 
            </tr>
        {% endfor %}
        </table>
{% endblock %}

templates/teacher/forum_content.html
{% extends "base.html" %}
{% load tag %}
{% block title %} Teachers {% endblock %}
{% block content %}
        <a href="/teacher/forum/content/add/{{forum_id}}">新增素材</a><BR><BR>
        <table>
        {% for work in contents %}
              <tr><td><A href="/teacher/forum/content/delete/{{forum_id}}/{{work.id}}" onclick="return confirm('確定要刪除嗎?')"><img src="/static/images/delete.gif"></a>
              {% if work.content_type == 1 %}

              <a href="{{work.content_link}}" target="_blank">{% if work.content_title %}{{work.content_title}}{% else %}開啟連結{% endif %}</a>
                
              {% endif %}
              {% if work.content_type == 2 %}
              
              <iframe width="560" height="315" src="https://www.youtube.com/embed/{{work.content_youtube|number}}" frameborder="0" allowfullscreen></iframe>
                            
              {% endif %}
              {% if work.content_type == 3 %}
              <a href="/teacher/forum/download/{{work.id}}" target="_blank">{{work.content_title}}</a> 
                                            
              {% endif %}              
                </td></tr>
        {% endfor %}
        </table>
{% endblock %}
          

templates/teacher/forum_form.html
{% extends "base.html" %}
{% block content %}
         <form action=""  method="post"  enctype="multipart/form-data">
           <input type=hidden name=content_type value="1">
           <input type=hidden name=forum_id value={{forum_id}}>
           文章褾題:<input id="id_content_title" maxlength="250" name="content_title" type="text" placeholder="開啟連結">
           文章網址:<input id="id_content_link" maxlength="250" name="content_link" type="text"> {% csrf_token %}<input type="submit" value="送出">
        </form>
<BR><BR>
<!--------------------------------------------------------->
         <form action=""  method="post" enctype="multipart/form-data">
           <input type=hidden name=content_type value="2">
           <input type=hidden name=forum_id value={{forum_id}}>           
           Youtube:<input id="id_content_youtube" maxlength="250" name="content_youtube" type="text" /><input type="submit" value="送出">
            {% csrf_token %}         
        </form>
<BR><BR>
<!--------------------------------------------------------->
         <form action=""  method="post" enctype="multipart/form-data" >
           <input type=hidden name=content_type value="3">
           <input type=hidden name=forum_id value={{forum_id}}>           
           檔案:<input id="id_content_file" name="content_file" type="file"/><input type="submit" value="送出">
            {% csrf_token %}         
        </form>
{% endblock %}

templates/teacher/forum_list.html
{% extends "base.html" %}
{% block title %} Teachers {% endblock %}
{% block content %}
        <a href="/teacher/forum/add/{{classroom_id}}">新增討論</a><BR><BR>
        <table>
            <tr>
                <td>名稱</td>
                <td>時間</td>				
                <td colspan=3>功能</td>
        {% for work in works %}
            <tr>
            <td>{{work.title}}</td>
			<td>{{work.time}}</td>
            <td><a href="/teacher/forum/content/{{work.id}}">素材</a></td>              
            <td><a href="/teacher/forum/class/{{classroom_id}}/{{work.id}}">評分</a></td>
            <td><a href="/student/forum/memo/{{classroom_id}}/{{work.id}}">心得</a></td>			
            </tr>
        {% endfor %}
        </table>
{% endblock %}

templates/teacher/twork_class.html
{% extends "base.html" %}
{% block title %}Create a question{% endblock %}
{% block content %}
        {{lesson.1}}
        <br>
        {{lesson.2}}
		<BR>
		 <a href="/teacher/work/group/{{index}}/{{classroom_id}}">組別</a>
        <table>
        <tr>
            <td>學生</td>
            <td>組別</td>
            <td>功能</td>
        </tr>
        {% for list in classmate_work  %}
                <tr>
                <td>
                {% if not list.1.number = "0" %} 
                        {{list.0.seat}})<a href="/teacher/scoring/{{classroom_id}}/{{list.0.student.id}}/{{index}}">{{list.0.student.first_name}}-{% if list.1.code %}{{list.1.publication_date}}{% endif %}
                    {% if list.1.score > 0 %}
                        ({{list.1.score}}-{{list.3}})
                    {%  endif %}
                        </a><br/>
                {% else %}
                        {{list.0.seat}}){{list.0.student.first_name}}<br/>
                {% endif %}
                </td>
                <td>{{list.4}}</td>
                <td>{% if list.2 > 0 %}小老師<a href="/teacher/assistant_cancle/{{list.0.classroom.id}}/{{list.0.student.id}}/{{index}}">(取消)</a>{% else %}<a href="/teacher/assistant/{{list.0.classroom.id}}/{{list.0.student.id}}/{{index}}">設定為小老師</a>{% endif %}</td>
                </tr>
        {% endfor %}
        </table>
{% endblock %}

templates/teacher/twork_list.html
{% extends "base.html" %}
{% block title %} Teachers {% endblock %}
{% block content %}
        <a href="/teacher/work/add/{{classroom_id}}">新增作業</a><BR><BR>
        <table>
            <tr>
                <td>名稱</td>
                <td>時間</td>				
                <td colspan=2>功能</td>
        {% for work in works %}
            <tr>
            <td>{{work.title}}</td>
			<td>{{work.time}}</td>
            <td><a href="/teacher/work/class/{{classroom_id}}/{{work.id}}">評分</a></td>
            <td><a href="/student/work/memo/{{classroom_id}}/{{work.id}}">心得</a></td>			
            </tr>
        {% endfor %}
        </table>
{% endblock %}